baseURL = "https://imagicthecat.thul.fr"
title = "Imagic"
theme = "m10c"
paginate = 8
defaultContentLanguage = 'fr'

[languages]
  [languages.fr]
    languageCode = 'fr-FR'
    languageName = "Français"
    weight = 0

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "À propos"
    url = "/about/"
    weight = 3

[params]
  author = "Imagic"
  description = "Rêveur / Développeur de l'ombre."
  favicon = '/icon.png'
  avatar = '/avatar.png'
  menu_item_separator = " - "
  [[params.social]]
    icon = "code"
    name = "Projets / Dépôts"
    url = "https://imagicthecat.thul.fr/fossils/"
  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/ImagicTheCat"
  [[params.social]]
    icon = "mail"
    name = "Email"
    url = "mailto:imagicthecat@gmail.com"
  [[params.social]]
    icon = "key"
    name = "Clé PGP/GPG"
    url = "/pgp-key.txt"
  [[params.social]]
    icon = "rss"
    name = "Flux RSS"
    url = "/index.xml"

  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#afbac4"
    lightestColor = "#ffffff"
    primaryColor = "#9e76fa"

[markup]
  [markup.highlight]
    style = 'dracula'

